// TODO(SET SORT AND FILTER ACTION TYPES)
// TODO(SET MAP ACTION TYPES)

export const DATA_LOADING = 'DATA_LOADING';

export const GET_PARKS = 'GET_PARKS';
export const GET_PARKS_SUCCESS = 'GET_PARKS_SUCCESS';
export const GET_PARKS_FAIL = 'GET_PARKS_FAIL';

export const GET_CAMPGROUNDS = 'GET_CAMPGROUNDS';
export const GET_CAMPGROUNDS_SUCCESS = 'GET_CAMPGROUNDS_SUCCESS';
export const GET_CAMPGROUNDS_FAIL = 'GET_CAMPGROUNDS_FAIL';

export const GET_VCENTER = 'GET_VCENTER';
export const GET_VCENTER_SUCCESS = 'GET_VCENTER_SUCCESS';
export const GET_VCENTER_FAIL = 'GET_VCENTER_FAIL';

export const GET_EVENTS = 'GET_EVENTS';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_FAIL = 'GET_EVENTS_FAIL';

export const GET_NEWS = 'GET_NEWS';
export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS';
export const GET_NEWS_FAIL = 'GET_NEWS_FAIL';

export const GET_ALERTS = 'GET_ALERTS';
export const GET_ALERTS_SUCCESS = 'GET_ALERTS_SUCCESS';
export const GET_ALERTS_FAIL = 'GET_ALERTS_FAIL';

// --------SET--------//
export const SET_STATE = 'SET_STATE';
export const SET_STATE_SUCCESS = 'SET_STATE_SUCCESS';
export const SET_STATE_FAIL = 'SET_STATE_FAIL';

export const SET_PARK = 'SET_PARK';
export const SET_PARK_SUCCESS = 'SET_PARK_SUCCESS';
export const SET_PARK_FAIL = 'SET_PARK_FAIL';